# Generated by Django 5.0.2 on 2024-02-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryBook',
            fields=[
                ('title', models.CharField(max_length=511)),
                ('author', models.CharField(max_length=511)),
                ('isbn', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('available', models.BooleanField()),
            ],
            options={
                'ordering': ['author'],
                'unique_together': {('title', 'author')},
            },
        ),
    ]
